openapi: 3.0.3
info:
  title: PDRRMO
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://api.pdrrmo.local'
paths:
  /v1/auth/login:
    post:
      summary: "Login user\n\nLogin using email and password"
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: nulla
                password:
                  type: string
                  description: ''
                  example: hic
              required:
                - email
                - password
      security: []
  /v1/auth/logout:
    post:
      summary: "Logout\n\nLogout user"
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Authentication
  /v1/registration:
    post:
      summary: 'User Sign Up'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: ''
                  example: molestias
                middlename:
                  type: string
                  description: ''
                  example: excepturi
                lastname:
                  type: string
                  description: ''
                  example: et
                email:
                  type: string
                  description: ''
                  example: cum
                password:
                  type: string
                  description: ''
                  example: rerum
                password_confirmation:
                  type: string
                  description: ''
                  example: qui
                group_id:
                  type: integer
                  description: ''
                  example: 19
              required:
                - firstname
                - lastname
                - email
                - password
      security: []
  '/v1/email/verify/{id}':
    get:
      summary: 'Mark the authenticated userâ€™s email address as verified.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the verify.'
        example: voluptatem
        required: true
        schema:
          type: string
  '/v1/email/resend/{id}':
    get:
      summary: 'Resend the email verification notification.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the resend.'
        example: nisi
        required: true
        schema:
          type: string
  /v1/password/link:
    post:
      summary: 'Send email reset link'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Passwords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: neque
              required:
                - email
      security: []
  /v1/password/reset:
    post:
      summary: 'Reset Password'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Passwords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: distinctio
                token:
                  type: string
                  description: ''
                  example: voluptates
                password:
                  type: string
                  description: ''
                  example: recusandae
                password_confirmation:
                  type: string
                  description: ''
                  example: qui
              required:
                - id
                - token
                - password
                - password_confirmation
      security: []
tags:
  -
    name: Authentication
    description: ''
  -
    name: Endpoints
    description: ''
  -
    name: Passwords
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
